2022-05-11 09:50:20.276 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 09:50:20.277 | WARNING  | pysgems.sgems.sg:__init__:41 - GSTLAPPLIHOME environment variable does not exist
2022-05-11 09:50:20.277 | ERROR    | pysgems.io.sgio:datread:24 - File D:\MyProject\Python\PycharmProjects\DataProcessing\Microtremor\TestProgramSet\GeoStat\datasets\demo_kriging\sgems_dataset.eas not found.
2022-05-11 09:52:09.714 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 09:52:09.714 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 09:52:09.714 | WARNING  | pysgems.sgems.sg:__init__:41 - GSTLAPPLIHOME environment variable does not exist
2022-05-11 09:52:09.714 | WARNING  | pysgems.sgems.sg:__init__:41 - GSTLAPPLIHOME environment variable does not exist
2022-05-11 09:59:45.352 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 09:59:45.353 | INFO     | pysgems.sgems.sg:__init__:44 - GSTLAPPLIHOME environment variable found
2022-05-11 09:59:45.353 | INFO     | pysgems.sgems.sg:__init__:60 - sgems exe file : sgems-x64.exe in E:\Program Files\SGeMS-x64-Beta
2022-05-11 09:59:45.354 | ERROR    | pysgems.io.sgio:datread:24 - File D:\MyProject\Python\PycharmProjects\DataProcessing\Microtremor\TestProgramSet\GeoStat\datasets\demo_kriging\sgems_dataset.eas not found.
2022-05-11 10:01:51.482 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 10:01:51.482 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 10:01:51.482 | INFO     | pysgems.sgems.sg:__init__:44 - GSTLAPPLIHOME environment variable found
2022-05-11 10:01:51.482 | INFO     | pysgems.sgems.sg:__init__:44 - GSTLAPPLIHOME environment variable found
2022-05-11 10:01:51.483 | INFO     | pysgems.sgems.sg:__init__:60 - sgems exe file : sgems-x64.exe in E:\Program Files\SGeMS-x64-Beta
2022-05-11 10:01:51.483 | INFO     | pysgems.sgems.sg:__init__:60 - sgems exe file : sgems-x64.exe in E:\Program Files\SGeMS-x64-Beta
2022-05-11 10:02:45.744 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 10:02:45.744 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 10:02:45.744 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 10:02:45.744 | INFO     | pysgems.sgems.sg:__init__:44 - GSTLAPPLIHOME environment variable found
2022-05-11 10:02:45.744 | INFO     | pysgems.sgems.sg:__init__:44 - GSTLAPPLIHOME environment variable found
2022-05-11 10:02:45.744 | INFO     | pysgems.sgems.sg:__init__:44 - GSTLAPPLIHOME environment variable found
2022-05-11 10:02:45.745 | INFO     | pysgems.sgems.sg:__init__:60 - sgems exe file : sgems-x64.exe in E:\Program Files\SGeMS-x64-Beta
2022-05-11 10:02:45.745 | INFO     | pysgems.sgems.sg:__init__:60 - sgems exe file : sgems-x64.exe in E:\Program Files\SGeMS-x64-Beta
2022-05-11 10:02:45.745 | INFO     | pysgems.sgems.sg:__init__:60 - sgems exe file : sgems-x64.exe in E:\Program Files\SGeMS-x64-Beta
2022-05-11 10:04:10.182 | ERROR    | pysgems.io.sgio:datread:24 - File D:\MyProject\Python\PycharmProjects\DataProcessing\Microtremor\TestProgramSet\GeoStat\datasets\demo_kriging\sgems_dataset.eas not found.
2022-05-11 10:04:10.182 | ERROR    | pysgems.io.sgio:datread:24 - File D:\MyProject\Python\PycharmProjects\DataProcessing\Microtremor\TestProgramSet\GeoStat\datasets\demo_kriging\sgems_dataset.eas not found.
2022-05-11 10:04:10.182 | ERROR    | pysgems.io.sgio:datread:24 - File D:\MyProject\Python\PycharmProjects\DataProcessing\Microtremor\TestProgramSet\GeoStat\datasets\demo_kriging\sgems_dataset.eas not found.
2022-05-11 10:04:45.864 | ERROR    | pysgems.io.sgio:datread:24 - File D:\MyProject\Python\PycharmProjects\DataProcessing\Microtremor\TestProgramSet\GeoStat\datasets\demo_kriging\sgems_dataset.eas not found.
2022-05-11 10:04:45.864 | ERROR    | pysgems.io.sgio:datread:24 - File D:\MyProject\Python\PycharmProjects\DataProcessing\Microtremor\TestProgramSet\GeoStat\datasets\demo_kriging\sgems_dataset.eas not found.
2022-05-11 10:04:45.864 | ERROR    | pysgems.io.sgio:datread:24 - File D:\MyProject\Python\PycharmProjects\DataProcessing\Microtremor\TestProgramSet\GeoStat\datasets\demo_kriging\sgems_dataset.eas not found.
2022-05-11 10:07:19.399 | INFO     | pysgems.io.sgio:loader:187 - Data loaded.
2022-05-11 10:07:19.399 | INFO     | pysgems.io.sgio:loader:187 - Data loaded.
2022-05-11 10:07:19.399 | INFO     | pysgems.io.sgio:loader:187 - Data loaded.
2022-05-11 10:07:19.414 | INFO     | pysgems.io.sgio:__init__:165 - 2D dataset detected.
2022-05-11 10:07:19.414 | INFO     | pysgems.io.sgio:__init__:165 - 2D dataset detected.
2022-05-11 10:07:19.414 | INFO     | pysgems.io.sgio:__init__:165 - 2D dataset detected.
2022-05-11 10:15:20.132 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-11 10:15:20.132 | INFO     | pysgems.sgems.sg:__init__:44 - GSTLAPPLIHOME environment variable found
2022-05-11 10:15:20.133 | INFO     | pysgems.sgems.sg:__init__:60 - sgems exe file : sgems-x64.exe in E:\Program Files\SGeMS-x64-Beta
2022-05-11 10:15:20.134 | INFO     | pysgems.io.sgio:loader:187 - Data loaded.
2022-05-11 10:15:20.135 | INFO     | pysgems.io.sgio:__init__:165 - 2D dataset detected.
2022-05-14 10:17:54.560 | INFO     | pysgems.sgems.sg:__init__:33 - Project sgems_test initiated
2022-05-14 10:17:54.560 | INFO     | pysgems.sgems.sg:__init__:44 - GSTLAPPLIHOME environment variable found
2022-05-14 10:17:54.561 | INFO     | pysgems.sgems.sg:__init__:60 - sgems exe file : sgems-x64.exe in E:\Program Files\SGeMS-x64-Beta
2022-05-14 10:17:54.562 | INFO     | pysgems.io.sgio:loader:187 - Data loaded.
2022-05-14 10:17:54.563 | INFO     | pysgems.io.sgio:__init__:165 - 2D dataset detected.
